// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TicketService.Data;

#nullable disable

namespace TicketService.Migrations
{
    [DbContext(typeof(TicketDbContext))]
    [Migration("20251112195841_AddOrganizationSlaAndEnhancements")]
    partial class AddOrganizationSlaAndEnhancements
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Shared.Models.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("contact_email");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("contact_phone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid?>("SlaId")
                        .HasColumnType("uuid")
                        .HasColumnName("sla_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_organizations_is_active");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_organizations_name");

                    b.HasIndex("SlaId")
                        .HasDatabaseName("ix_organizations_sla_id");

                    b.ToTable("organizations", (string)null);
                });

            modelBuilder.Entity("Shared.Models.SLA", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("ResolutionTimeCritical")
                        .HasColumnType("integer")
                        .HasColumnName("resolution_time_critical");

                    b.Property<int>("ResolutionTimeHigh")
                        .HasColumnType("integer")
                        .HasColumnName("resolution_time_high");

                    b.Property<int>("ResolutionTimeLow")
                        .HasColumnType("integer")
                        .HasColumnName("resolution_time_low");

                    b.Property<int>("ResolutionTimeMedium")
                        .HasColumnType("integer")
                        .HasColumnName("resolution_time_medium");

                    b.Property<int>("ResponseTimeCritical")
                        .HasColumnType("integer")
                        .HasColumnName("response_time_critical");

                    b.Property<int>("ResponseTimeHigh")
                        .HasColumnType("integer")
                        .HasColumnName("response_time_high");

                    b.Property<int>("ResponseTimeLow")
                        .HasColumnType("integer")
                        .HasColumnName("response_time_low");

                    b.Property<int>("ResponseTimeMedium")
                        .HasColumnType("integer")
                        .HasColumnName("response_time_medium");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_slas_is_active");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_slas_name");

                    b.ToTable("slas", (string)null);
                });

            modelBuilder.Entity("Shared.Models.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("color");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_tags_name");

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("Shared.Models.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssignedAgentId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_agent_id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("priority");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<Guid?>("SlaId")
                        .HasColumnType("uuid")
                        .HasColumnName("sla_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AssignedAgentId")
                        .HasDatabaseName("ix_tickets_assigned_agent_id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_tickets_created_at");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_tickets_customer_id");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_tickets_organization_id");

                    b.HasIndex("Priority")
                        .HasDatabaseName("ix_tickets_priority");

                    b.HasIndex("SlaId")
                        .HasDatabaseName("ix_tickets_sla_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_tickets_status");

                    b.ToTable("tickets", (string)null);
                });

            modelBuilder.Entity("Shared.Models.TicketAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<string>("DownloadUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("download_url");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size_bytes");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("storage_path");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticket_id");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.Property<Guid>("UploadedById")
                        .HasColumnType("uuid")
                        .HasColumnName("uploaded_by_id");

                    b.HasKey("Id");

                    b.HasIndex("TicketId")
                        .HasDatabaseName("ix_ticket_attachments_ticket_id");

                    b.HasIndex("UploadedAt")
                        .HasDatabaseName("ix_ticket_attachments_uploaded_at");

                    b.HasIndex("UploadedById")
                        .HasDatabaseName("ix_ticket_attachments_uploaded_by_id");

                    b.ToTable("ticket_attachments", (string)null);
                });

            modelBuilder.Entity("Shared.Models.TicketAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("action");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("FieldName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("field_name");

                    b.Property<string>("NewValue")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("new_value");

                    b.Property<string>("OldValue")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("old_value");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticket_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Action")
                        .HasDatabaseName("ix_ticket_audit_logs_action");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_ticket_audit_logs_created_at");

                    b.HasIndex("TicketId")
                        .HasDatabaseName("ix_ticket_audit_logs_ticket_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_ticket_audit_logs_user_id");

                    b.ToTable("ticket_audit_logs", (string)null);
                });

            modelBuilder.Entity("Shared.Models.TicketComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsInternal")
                        .HasColumnType("boolean")
                        .HasColumnName("is_internal");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticket_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_ticket_comments_created_at");

                    b.HasIndex("TicketId")
                        .HasDatabaseName("ix_ticket_comments_ticket_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_ticket_comments_user_id");

                    b.ToTable("ticket_comments", (string)null);
                });

            modelBuilder.Entity("ticket_tags", b =>
                {
                    b.Property<Guid>("tag_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ticket_id")
                        .HasColumnType("uuid");

                    b.HasKey("tag_id", "ticket_id");

                    b.HasIndex("ticket_id");

                    b.ToTable("ticket_tags");
                });

            modelBuilder.Entity("Shared.Models.Organization", b =>
                {
                    b.HasOne("Shared.Models.SLA", "Sla")
                        .WithMany("Organizations")
                        .HasForeignKey("SlaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Sla");
                });

            modelBuilder.Entity("Shared.Models.Ticket", b =>
                {
                    b.HasOne("Shared.Models.Organization", "Organization")
                        .WithMany("Tickets")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Shared.Models.SLA", "Sla")
                        .WithMany()
                        .HasForeignKey("SlaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Organization");

                    b.Navigation("Sla");
                });

            modelBuilder.Entity("Shared.Models.TicketAttachment", b =>
                {
                    b.HasOne("Shared.Models.Ticket", "Ticket")
                        .WithMany("Attachments")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Shared.Models.TicketAuditLog", b =>
                {
                    b.HasOne("Shared.Models.Ticket", "Ticket")
                        .WithMany("AuditLogs")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Shared.Models.TicketComment", b =>
                {
                    b.HasOne("Shared.Models.Ticket", "Ticket")
                        .WithMany("Comments")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("ticket_tags", b =>
                {
                    b.HasOne("Shared.Models.Tag", null)
                        .WithMany()
                        .HasForeignKey("tag_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shared.Models.Ticket", null)
                        .WithMany()
                        .HasForeignKey("ticket_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Shared.Models.Organization", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Shared.Models.SLA", b =>
                {
                    b.Navigation("Organizations");
                });

            modelBuilder.Entity("Shared.Models.Ticket", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("AuditLogs");

                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
